---
version: '3'

services:
  cms-back-dev:
    build:
      context: ./cms-back
      dockerfile: Dockerfile-dev
    environment:
      - PORT=8081
      - DATABASE_HOST=cloud-sql-proxy
      - DATABASE_USER=devsql
      - DATABASE_PASSWORD=berglas://cms-secrets/cms-devsql-password
      - DATABASE_NAME=dev_centralmanagementsystem
      - APP_ENV=dev
      - GOOGLE_APPLICATION_CREDENTIALS=/config.json
    entrypoint: /bin/berglas exec --local --
    command: sh run.sh
    volumes:
      - ./cms-sql-dev-key.json:/config.json
      - ./cms-back:/home/python/app
    ports:
      - "8081:8081"
    depends_on:
      - cloud-sql-proxy

  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.14
    command: /cloud_sql_proxy -instances=central-management-system:us-central1:cms-back-tcr=tcp:0.0.0.0:3306 -credential_file=/config.json
    volumes:
      - ./cms-sql-dev-key.json:/config.json
    ports:
      - 3306:3306


  cms-front-dev:
    build:
      context: ./cms-front
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
