version: '3'

services:
  cms-back:
    build:
      context: .
    environment:
      - PORT=3000
      - DATABASE_HOST=cloud-sql-proxy
      - DATABASE_USER=devsql
      - DATABASE_PASSWORD=berglas://cms-secrets/cms-devsql-password
      - APP_ENV=staging
      - GOOGLE_APPLICATION_CREDENTIALS=/config.json
    volumes:
      - ./cms-sql-dev-key.json:/config.json
    ports:
      - "8081:3000"
    depends_on:
      - cloud-sql-proxy

  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.14
    command: /cloud_sql_proxy -instances=central-management-system:us-central1:cms-back-tcr=tcp:0.0.0.0:3306 -credential_file=/config.json
    volumes:
      - ./cms-sql-dev-key.json:/config.json
    ports:
      - 3306:3306